---

- name: "Generate a temp dir to be used for dependencies"
  tempfile:
    state: directory
  register: tmp_dir
  notify:
    - Clean up temporary dependency dir
  when:
    - tmp_dep_dir is undefined

- name: "Store away the temporary directory path"
  set_fact:
    tmp_dep_dir: "{{ tmp_dir.path }}/"
  when:
    - tmp_dep_dir is undefined

- set_fact:
    galaxy_requirements: "{{ dependencies.galaxy_requirements | default([]) }}"

- name: "Compose galaxy_requirements file if galaxy_sources is set"
  block:
    - tempfile:
        state: file
        suffix: .yml
      register: tmp_galaxy_file
    - template:
        src: yaml_file.j2 
        dest: "{{ tmp_galaxy_file.path }}"
      vars:
        yaml_content: "{{ dependencies.galaxy_sources }}"
    - set_fact:
        galaxy_requirements: "{{ galaxy_requirements + [ tmp_galaxy_file.path ] }}"
  when:
    - dependencies.galaxy_sources is defined
    - dependencies.galaxy_sources|length > 0

- name: "Run ansible-galaxy to pull in dependency roles"
  command: >
    ansible-galaxy install -r "{{ item }}" -p "{{ tmp_dep_dir }}"
  with_items:
    - "{{ galaxy_requirements }}"

- name: "Clean-up temporary file from above - if needed"
  file:
    path: "{{ tmp_galaxy_file.path }}"
    state: absent
  ignore_errors: True
  when:
    - tmp_galaxy_file is defined
    - tmp_galaxy_file.path|trim != '' 
