---

# This is a bit of a "hack" to pass the variables in to the role below
# It would be nice if we could something like `vars: {{ step.vars }}`,
# but it unfortunately generates an error with Ansible.
- name: "Set facts to make variables available to the role"
  set_fact:
    "{{ var.key }}": "{{ var.value }}"
  with_dict: "{{ step.vars | default({}) }}"
  loop_control:
    loop_var: var

- set_fact:
    saved_ansible_roles_path: "{{ lookup('env', 'ANSIBLE_ROLES_PATH') }}"

- name: "Add temporary path to the ANSIBLE_ROLES_PATH to let it find pre/post steps roles"
  setup:
  environment:
    ANSIBLE_ROLES_PATH: "{{ tmp_dep_dir + ':' + saved_ansible_roles_path }}"

- name: "Include the pre/post step role"
  include_role:
    name: "{{ step.role }}"
  when:
    - step is defined
    - step.role is defined
    - step.role|trim != ''

- name: "Restore ANSIBLE_ROLES_PATH to remove temporary location"
  setup:
  environment:
    ANSIBLE_ROLES_PATH: "{{ saved_ansible_roles_path }}"

- name: "Clear facts to ensure that they don't carry over"
  set_fact:
    "{{ var.key }}": ""
  with_dict: "{{ step.vars | default({}) }}"
  loop_control:
    loop_var: var
