---
- name: Exit if ansible version doesn't meet minimum requirements
  fail:
    msg: "openshift-applier requires at least Ansible 2.5 in order to proceed"
  when:
  - "ansible_version.full is version('2.5','<')"


- name:  "Determine oc version"
  shell: "oc version | sed -ne 's/^oc v*\(.*\)+.*$/\1/p'" 
  register: oc_vers_check

- name: "Determine unknown param flag"
  set_fact:
    oc_ignore_unknown_parameters: false
  when:
  - oc_vers_check is defined
  - oc_vers_check.stdout is defined
  - oc_vers_check.stdout|trim != ""
  - oc_vers_check.stdout is version('3.6','<=')
